Assignment_2/Controllers/TrainerController.cs
using Assignment_2.Models;
using Assignment_2.Repositories;
using System.Web.Mvc;

namespace Assignment_2.Controllers
{
    public class TrainerController : Controller
    {
        private readonly TrainerCrudRepository _trainerRepos;
        // GET: Trainer

        public TrainerController()
        {
            _trainerRepos = new TrainerCrudRepository();
        }

        public ActionResult Index()
        {
            return View();
        }

        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            var viewModel = _trainerRepos.MatchTrainerViewModel(id);
            return View(viewModel);
        }

        // GET: Trainer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Trainer/Create
        [HttpPost]
        public ActionResult Create(Trainer trainer)
        {
            if (!ModelState.IsValid)
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            try
            {
                _trainerRepos.Create(trainer);
                _trainerRepos.Save();

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View("Create", trainer);
            }
        }

        // GET: Trainer/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Trainer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Trainer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Trainer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _trainerRepos.Dispose();
            base.Dispose(disposing);
        }
    }
}

Assignment_2/Views/Shared/Navbar.cshtml
<div class="navbar-fixed-bottom class circle container-fluid"  >
    <nav class="navbar navbar-expand-lg navbar-light bg-light "  >
        <div class="navbar navbar-default focus class circle" >
            <div>
                <div class="navbar-header" >

                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Tk stands for Trainer Kreator™ ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" >

                        <li> <strong>@Html.ActionLink("Create Trainer Form", "Create", "Trainer", new { area = "" }, new
                        {
                            @style = "margin-top:10px;font-size:200%;color:white;background-color:;" })</strong></li>
                    </ul>
                </div>
            </div>
           
        </div>
    </nav>
</div>

Assignment_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head >
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Trainer Kreator </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div @*class="container"*@>
        <div>
            @RenderBody()
            <hr />
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
        <footer>
            <p>&copy; @DateTime.Now.Kind Time: @DateTime.Now.Hour : @DateTime.Now.Minute - TrainerKreator™ Application</p>
        </footer>
        </div>
    </body>
    
</html>