Assignment_2/Controllers/HomeController.cs
using Assignment_2.Repositories;
using Assignment_2.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Assignment_2.Controllers
{
    public class HomeController : Controller 
    {
        private readonly TrainerCrudRepository _trainerRepos;
        // GET: Trainer

        public HomeController()
        {
            _trainerRepos = new TrainerCrudRepository();
        }

        public ActionResult Index()
        {
            var model = new TrainerViewModel
            {
                Trainers = _trainerRepos.GetAll().ToList()
            };
            return View(model);
        }

        
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _trainerRepos.Dispose();
            base.Dispose(disposing);
        }
    }
}

Assignment_2/Controllers/PartialController.cs
using Assignment_2.Repositories;
using Assignment_2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_2.Controllers
{
    public class PartialController : HomeController
    {
      
            private readonly TrainerCrudRepository _trainerRepos;
            // GET: Trainer

            public PartialController()
            {
                _trainerRepos = new TrainerCrudRepository();
            }


            public ActionResult GetAction()
            {
                 var partialView =    _trainerRepos.GetListOfTrainers();
 
                return View(partialView);
            }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _trainerRepos.Dispose();
            }
            base.Dispose(disposing);
        }

    }
    }

Assignment_2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Assignment_2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Assignment_2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div @*class="container row circle  class"*@>
   

        <div class="class circle container " style="justify-content:stretch;padding:15%;background-image: url('/img/paisaje-de-rick-y-morty-9415.jpg');" );>
     

            @Html.Partial("Navbar")
            <div>
                <div class="col-md-4" style="padding:10%">
                    <a class="navbar-fixed-top btn-default class circle " style="padding:5px" href="https://github.com/GiannisMonastiriotis/Assignment_2.git">&raquo;Get This Project In Git. We love it here in People Cert!</a>
                </div>
            </div>
        </div>
    </div>

    <p style="padding-top:2%"> </p>
    <div class="class circle no-repeat cat-wrap "style="display:flex";>
        <img class="cat-bg" style="background-image: url('/img/programmer-here-not-a-magician.jpg')" />
        <div class="aftercat-content">
            <table class="table table-bordered tableGod">
                <thead class="tableGod">


                    <tr style="font-size:140%">
                        <th scope="col" >#</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Adress</th>
                        <th scope="col">Age</th>
                        <th scope="col">Details</th>
                        <th scope="col">Email Adress</th>
                        <th scope="col">Salary</th>
                        <th scope="col">Phone Num.</th>
                        <th scope="col">Gender</th>

                    </tr>


                </thead>

                @{
                    Html.RenderAction("GetAction", "Partial", new { area = "" });
                }

            </table>
        </div>
    </div>
 
</div>